### ISSUE TITLE
为啥不用/padavanonly/immortalwrt这个库了啊

### ISSUE THREAD

**Issue by qwerttvv** [KevinMX/Railgun#1]
请问下目前7621的openwrt用哪个库性能更好一些，更稳定一些，不考虑无线的情况下

我看有lean，/padavanonly/immortalwrt，/aiamadeus/lede/tree/ramips

**Comment by KevinMX** [comment]
A1. 目前不使用 [padavanonly/immortalwrt](https://github.com/padavanonly/immortalwrt) 是因为尚未做无线性能（尤其是无线拉满的情况下，CPU 占用情况）的对比测试，后面有时间会安排上，预计年前搞定。目前如有需要可用 [KevinMX/actions-immortalwrt-mtk-sdk-phicomm-k2p](https://github.com/KevinMX/actions-immortalwrt-mtk-sdk-phicomm-k2p) 或自行编译。
A2. 不考虑无线的情况下其实都大差不差，但 Lean 的更新更快。
A3. [aiamadeus/lede](https://github.com/aiamadeus/lede) 和 Lean 主线区别并不大，这位也是 Lean 源码贡献者之一，大部分 commit 都会合并过去，用这个和用 Lean 的不会有太大区别。

**Comment by KevinMX** [comment]
新 3 的话，mt76 开源驱动之前用过一段时间（因为支持 MT7612 的 802.11kvr），相信也能看到我 Revert 了，会时不时报错然后重启无线，闭源驱动就没这个问题，但是闭源驱动的 7612 不支持 802.11kvr。

**Comment by KevinMX** [comment]
> A1. 目前不使用 [padavanonly/immortalwrt](https://github.com/padavanonly/immortalwrt) 是因为尚未做无线性能（尤其是无线拉满的情况下，CPU 占用情况）的对比测试，后面有时间会安排上，预计年前搞定。

已测试在 Wi-Fi 拉满情况下，在斐讯 K2P 上[padavanonly/immortalwrt](https://github.com/padavanonly/immortalwrt) 会比 Lean lede 稍快 100Mbps 左右，（测试方法为，上级路由开 librespeed 服务器，笔记本 AX210 贴脸连到 K2P 的 5GHz 频段，全默认设置，测速结果， lean 源码上下行均 <600Mbps，padavanonly 源码下行 ~695Mbps，上行 ~725Mbps），且多核负载均衡更好，晚些会将 Actions CI 切换至 [padavanonly/immortalwrt](https://github.com/padavanonly/immortalwrt) 源码。
受影响的机型包括：新路由 3、斐讯 K2P。

**Comment by KevinMX** [comment]
> 有几个kmod我编译不进去，但是看你这边是编译进去了，不知道为啥，有时间了能不能帮咱瞧瞧，新3这家伙，加密还是chacha20吧…… CONFIG_PACKAGE_kmod-crypto-lib-chacha20=y CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=y CONFIG_PACKAGE_kmod-crypto-lib-curve25519=y CONFIG_PACKAGE_kmod-crypto-lib-poly1305=y

这几个其实吧也就 VPN 应用能用得上（Strongswan），可能我没清理干净，然后我记得 MT7621 默认也不带 chacha20 系列 crypto 加速的……其实无所谓的……现在我都是直接 WireGuard 完事了。

**Comment by KevinMX** [comment]
> 就是科学上网用的这个
科学上网是用不到 MTK EIP-93 硬件加速的，然后和 kmod 也没有关系，并不一定需要编译进去。

**Comment by KevinMX** [comment]
> 晚些会将 Actions CI 切换至 [padavanonly/immortalwrt](https://github.com/padavanonly/immortalwrt) 源码。 受影响的机型包括：新路由 3、斐讯 K2P。

Done

**Comment by KevinMX** [comment]
> 还请问下 CONFIG_DEVEL=y CONFIG_CCACHE=y 这俩是干啥的啊 带devel编译出来的也没见固件文件变大，带ccache的也没见编译速度快

你 `make menuconfig` 看一下就知道了。CCACHE 是在 `Advanced configuration options (for developers)` 中的，对应的就是 `CONFIG_DEVEL=y`。先勾选这个菜单，然后才能开启 CCACHE。多次编译、同一架构的情况下是会有性能提升的。Actions CI 的话，后面我会测试下全新编译有无性能损失，如果有的话会考虑去掉。

**Comment by KevinMX** [comment]
> > > 还请问下 CONFIG_DEVEL=y CONFIG_CCACHE=y 这俩是干啥的啊 带devel编译出来的也没见固件文件变大，带ccache的也没见编译速度快
> > 
> > 
> > 你 `make menuconfig` 看一下就知道了。CCACHE 是在 `Advanced configuration options (for developers)` 中的，而这个菜单本身对应的就是 `CONFIG_DEVEL=y`。先勾选这个菜单，然后才能开启 CCACHE。多次编译、同一架构的情况下是会有性能提升的。Actions CI 的话，后面我会测试下全新编译有无性能损失，如果有的话会考虑去掉。
> 
> 我跑了俩，正在试，一会儿看看啥情况

测试结束。
编译机：机械革命/Mechrevo Code 01 Ver 2.0, Ryzen 7 6800H, ZHITAI TiPlus 7100 1TB NVMe SSD, Arch Linux (with linux 6.0.9-1-lily)
编译参数：time make -j$(nproc) V=s
编译时间取 time 中的 `real` 时间，即 `make` 命令开始到结束的时间。

|ccache 开关, 次数|编译时间|
|-|-|
|ccache off, 1st|14m53.083s|
|ccache off, 2nd|1m7.845s|
|ccache on, 1st|17m1.500s|
|ccache on, 2nd|1m6.966s|

似乎测试结果完全推翻了我先前的想法啊。那就暂时禁用掉 ccache 吧。
