### ISSUE TITLE
padavanonly/immortalwrt 这个源码可以开KVR吗？

### ISSUE THREAD

**Issue by zcmi** [KevinMX/Railgun#2]
好像后台无线设置没看到KVR的选项，WINFI查看也没有。设备是newifi3，其他固件好像支持K。还有个K2P没测试。

lede和原生的openwrt好像设置密码的时候可以选择开启KVR。不知道这个固件是不是其他的打开方式或者没有

**Comment by KevinMX** [comment]
A1: 新 3 7603 闭源驱动支持 802.11k/v/r，7612 不支持；mt76 开源驱动同时支持 7603/7612 的 802.11k/v/r，但并不稳定，先前使用 Lean 源码时，新 3 在开源 mt76 驱动下会频繁出现断流/WiFi 重启现象，个人不推荐使用。
luci-app-mtwifi 暂不支持配置，如需开启 7603 2.4GHz 的 802.11k/v/r 支持，请尝试在 2.4GHz 无线高级设置的无线参数中加入：
```
RRMEnable=1
FtSupport=1
WNMEnable=1
```
此外可能需要手动安装 mtkiappd。请参考本仓库 K2P 的配置方法。如有需要我也可把 mtkiappd 的 ipk 包发上来。不过，2.4GHz 频段的无线漫游也没什么意义吧……

A2: K2P 已默认开启 802.11k/v/r，可放心使用，如图。
![image](https://user-images.githubusercontent.com/17025286/213129229-c65cfd5c-6dcc-456f-8f8c-9b8be51c2782.png)
移动域为 5254。（注意 WinFi 里是反过来的）
![image](https://user-images.githubusercontent.com/17025286/213129775-f29ede74-dd15-44a2-84a3-2784b8dd2b42.png)

PS: 802.11r 对于无线漫游来说并不是必须，大多数情况下有 k/v 即可。

**Comment by zcmi** [comment]
> 
谢谢大佬解答，刚刷了k2p，成功开启KV
