### ISSUE TITLE
似乎在同时开启2.4G/5G的情况下，2.4G的k/r会失效

### ISSUE THREAD

**Issue by f0re1gnKey** [KevinMX/Railgun#3]
WinFi测得，路由器K2P
![QQ截图20230206182324](https://user-images.githubusercontent.com/92533411/216947283-9a0b5d25-e5e0-4370-ab3d-b97e41b3f1e4.png)

**Comment by KevinMX** [comment]
注意到上游有更新相关代码，晚些查看。

**Comment by KevinMX** [comment]
请尝试最新版构建。

如果还是不能解决，那可能是闭源驱动本身的问题了，我这边也无能为力。

**Comment by KevinMX** [comment]
Hi, any update?

**Comment by KevinMX** [comment]
802.11 k/v/r 无线漫游 / 仅 AP 用途，请尝试 ImmortalWrt。
23.05.1 版本硬件加速正常工作，无线漫游正常。
