### ISSUE TITLE
请问如何生成R619ac的可用配置？

### ISSUE THREAD

**Issue by Luupw3d** [KevinMX/Railgun#5]
使用Lean源码make menuconfig生成的.config，覆盖项目中的.config，100%出现ath10k-ct编译失败的问题，但您提供的原始.config则不会存在此错误。请问您的.config是如何生成的？

**Comment by KevinMX** [comment]
`./scripts/diffconfig.sh > r619ac.seed`

**Comment by Luupw3d** [comment]
> `make menuconfig` # 手动生成配置 `./scripts/diffconfig.sh > r619ac.seed`

感谢回复。Lean的.config有近400k的体积，且使用其make menuconfig生成的配置文件会出现ath10k-ct编译错误的问题。请问您是否遇到过？

**Comment by KevinMX** [comment]
从未遇到过。

**Comment by Luupw3d** [comment]
> 从未遇到过。
> 
> 提示一下，`diffconfig.sh` 生成的配置是参考默认配置，在其基础上记录增减内容，也就是说如果 `menuconfig` 直接生成有问题，理论上把 `seed` 拖进去再 `menuconfig` 也是一样的。
> 
> 编译错误的话，可能是源代码有问题。我重新跑一下 CI 看看。

使用您的.config编译是正常的，但Lean项目中也有相关issue报告该问题（即ath10k-ct编译错误），详见：https://github.com/coolsnowwolf/lede/issues/10744
目前仍未找到解决方法，因此如果您也是menuconfig生成.config，却能避免该问题，我暂时排查不出问题在哪……

**Comment by KevinMX** [comment]
CI 构建已经开始，预计 2.5h 结束。我的建议，不如早点休息，明早起来再看看结果 :)

**Comment by Luupw3d** [comment]
> CI 构建已经开始，预计 2.5h 结束。我的建议，不如早点休息，明早起来再看看结果 :)

感谢！

**Comment by Luupw3d** [comment]
CI构建完毕无误，与我先前测试的结果是一样的，因此极有可能是我是用`menuconfig`生成的.config有问题。您的.config也是本地ubuntu通过menuconfig生成，后push至当前项目的吗？

**Comment by KevinMX** [comment]
> CI构建完毕无误，与我先前测试的结果是一样的，因此极有可能是我是用`menuconfig`生成的.config有问题。您的.config也是本地ubuntu通过menuconfig生成，后push至当前项目的吗？

是本地生成的，不过我是 Arch Linux。一般只有在有大改的时候才会更新。

**Comment by Luupw3d** [comment]
很奇怪，采用lean默认源码，不添加任何第三方包，错误依旧。已在Lean那边开了issue，这边就先关闭了，感谢您的测试与帮助。
