### ISSUE TITLE
大神,package/kernel/mt-drivers/mtkiappd, lede库这个文件夹似乎没有了

### ISSUE THREAD

**Issue by xuexijiaoben** [KevinMX/Railgun#8]
编译k2p
git_sparse_clone https://github.com/coolsnowwolf/lede lede package/lean/mt/mtkiappd package/kernel/mt-drivers/mtkiappd

大神，我看到你这里有添加lede 的package/kernel/mt-drivers/mtkiappd ，但我去lede里看，似乎已经没有这个文件夹了，这样编译出来的k2p还是完整的么，
谢谢啦

**Comment by KevinMX** [comment]
https://github.com/coolsnowwolf/lede/tree/master/package/lean/mt/mtkiappd
