### ISSUE TITLE
请求增加版本

### ISSUE THREAD

**Issue by xmyaaa** [KevinMX/Railgun#9]
大佬：我是用斐讯 K2P，您以前有ssrplus+(2022.08.21-1809-ssrplus版本),现在没有看到了，能否再恢复一下这个版本？，还有一个请求：因很多人没有公网IP，只有内网，wireguard这个就无法使用，而zerotier可以弥补，希望增加一个ShadowsocksR Plus+（含zerotier，文件传输.,去掉wireguard，网络唤醒,,其他功能可不改变）版本。后面贴上您以前版本的说明，谢谢！
2022.08.21-1809-ssrplus版本
ssr-plus版本
基于 ImmortalWrt 18.06-k5.4
LuCI:
luci-app-arpbind
luci-app-ddns
luci-app-ssr-plus / luci-app-passwall（二选一）
luci-app-turboacc
luci-app-udpxy
luci-app-upnp
luci-app-vlmcsd
luci-app-wireguard
luci-app-wol
luci-theme-atmaterial
非 LuCI 的其他系统组件：
xray-core (SSR Plus+ 为 1.5.9，passwall 为 1.5.5）
ipt2socks
cloudflare ddns
ipv6helper
zram-swap
TCP BBR
Fullcone NAT
MTK SDK HWNAT
802.11k/v/r
Linux 5.10

**Comment by KevinMX** [comment]
现在版本的 xray-core 太大了，塞不进去。

**Comment by xmyaaa** [comment]
K2P今天刷了最新版本,目前看还不错，尤其是sing-box，平均负载和CPU使用率比xray
小很多！，

**Comment by xmyaaa** [comment]
> 现在版本的 xray-core 已经完成了，塞不进去 。ZeroTier 我会考虑。

谢谢大佬回复！

**Comment by xmyaaa** [comment]
> 现在版本的 xray-core 已经完成了，塞不进去 。ZeroTier 我会考虑。
刚刚测试了，好像没有这个 xray-core，只有sing-box
，

**Comment by KevinMX** [comment]
选择 sing-box 是因为其已经覆盖了 Xray-core 的几乎所有功能，而又刚刚好够塞下 K2P 那可怜的 16M SPI Flash。

**Comment by xmyaaa** [comment]
> 另外早期版本没有留档，可以回退到对应提交尝试拉取配置自行编译。 当然，对应的ImmortalWrt源码库也需要回退。估计会比较麻烦，不建议尝试。晚点我看看能不能塞的下ZeroTier吧。

老大：我是小白，根本就不会编译，只能请求老大解决！

**Comment by xmyaaa** [comment]
> 选择sing-box是因为其已经覆盖了Xray-core的几乎所有功能，刚好够塞下K2P那可怜的16M SPI Flash。

是，刚刚测试，很不错！

**Comment by xmyaaa** [comment]
wireguard这个功能，用ssr-plus版本就可实现，而且设置好简单，我就是这样在外面用ssr-plus回家，只需要要一个ssr APP就可

**Comment by KevinMX** [comment]
> wireguard这个功能，用ssr-plus版本就可实现，而且设置好简单，我就是这样在外面用ssr-plus回家，只需要要一个ssr APP就可

ssr-plus 的 WireGuard 依赖 Xray-core 内部实现，即 wireguard-go。
sing-box 里面也集成了这个，但仅限出站，换句话说只能用来连别人，不能用来开服务端。
尝试裁剪了一下 sing-box 编译出来了一版。先试试？方便的话，看看剩余空间还有多大。
[openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.zip](https://github.com/KevinMX/Railgun/files/14295770/openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.zip)

**Comment by KevinMX** [comment]
另外补充一下，WireGuard 早就整合进了 Linux 内核，用户态的工具几乎不需要占用多少空间。这个功能不会删除。

**Comment by xmyaaa** [comment]
刚刚测试这个版本，
2024.02.08-1959-phicomm_k2p
passwall无法保存配置，并且打不开，路由器重启几次后，现象一样，个人判断好像是内存爆了，后面又改用14.5MB版本，可以正常使用了，目前在使用过程中发现开机时启动非常慢，进系统时平均负载和CPU使用率非常高，运行一段时间后就降下来了一些，
个人有个建议：因K2P只有16M，那可否在现有去掉大多数人用不上的功能？，这样可增加一些空间，也许运行时就不会卡了，比方去掉（udpxy，组播代理，网络唤醒，尤其是ChinaDNS-NG，这个功能用处不大，也许还会发生冲突）
以上仅供大佬参考决定。
目前可以的版本
类型	固件
文件名	openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.bin
大小	14.5MB (15205344B)
MD5 校验	86059b59401cd3edaefe1272017463e1

**Comment by xmyaaa** [comment]
> > wireguard这个功能，用ssr-plus版本就可实现，而且设置好简单，我就是这样在外面用ssr-plus回家，只需要要一个ssr APP就可
> 
> ssr-plus 的 WireGuard 依赖 Xray-core 内部实现，即 wireguard-go。 sing-box 里面也集成了这个，但仅限出站，换句话说只能用来连别人，不能用来开服务端。 尝试裁剪了一下 sing-box 编译出来了一版。先试试？方便的话，看看剩余空间还有多大。 [openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.zip](https://github.com/KevinMX/Railgun/files/14295770/openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.zip)

刚刚下了，也是15MB多，恐怕太大用不了，前面那个15MB的就用不了，只有14.5MB可用，现在正在用

**Comment by xmyaaa** [comment]
![Uploading 66.JPG…]()

**Comment by xmyaaa** [comment]
刚忘了讲，这个版本刷机的时候复位选择openwrt，布局选择斐讯

**Comment by xmyaaa** [comment]
> > wireguard这个功能，用ssr-plus版本就可实现，而且设置好简单，我就是这样在外面用ssr-plus回家，只需要要一个ssr APP就可
> 
> ssr-plus 的 WireGuard 依赖 Xray-core 内部实现，即 wireguard-go。 sing-box 里面也集成了这个，但仅限出站，换句话说只能用来连别人，不能用来开服务端。 尝试裁剪了一下 sing-box 编译出来了一版。先试试？方便的话，看看剩余空间还有多大。 [openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.zip](https://github.com/KevinMX/Railgun/files/14295770/openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.zip)

空闲空间: 99% (58.97 MB)
/dev/root	
/rom	
0.00 B / 13.00 MB	
100% (13.00 MB)
tmpfs	
/tmp	
58.52 MB / 59.34 MB	
1% (844.00 KB)
tmpfs	
/tmp/root	
58.96 MB / 59.34 MB	
1% (392.00 KB)	
overlayfs:/tmp/root	
/	
58.96 MB / 59.34 MB	
1% (392.00 KB)
tmpfs	
/dev	
512.00 KB / 512.00 KB	
0% (0.00 B)

IP段
192.168.1.1

passwall无法使用，现象和前面15MB的一样.也没有重置按键选项

ZeroTier 可正常运行

现改回14.5MB版本

**Comment by KevinMX** [comment]
> 刚刚测试这个版本， 2024.02.08-1959-phicomm_k2p passwall无法保存配置，并且打不开，路由器重启几次后，现象一样，个人判断好像是内存爆了，后面又改用14.5MB版本，可以正常使用了，目前在使用过程中发现开机时启动非常慢，进系统时平均负载和CPU使用率非常高，运行一段时间后就降下来了一些， 个人有个建议：因K2P只有16M，那可否在现有去掉大多数人用不上的功能？，这样可增加一些空间，也许运行时就不会卡了，比方去掉（udpxy，组播代理，网络唤醒，尤其是ChinaDNS-NG，这个功能用处不大，也许还会发生冲突） 以上仅供大佬参考决定。 目前可以的版本 类型 固件 文件名 openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.bin 大小 14.5MB (15205344B) MD5 校验 86059b59401cd3edaefe1272017463e1

udpxy, 组播代理，网络唤醒这三个我都需要用。
ChinaDNS-NG 是 passwall 强依赖，去不掉。
你在 passwall 内使用的节点类型是什么？

**Comment by KevinMX** [comment]
![image](https://github.com/KevinMX/Railgun/assets/17025286/a8bd5202-71fd-4e2c-97a7-0753a4c079f6)
ZeroTier 一个包刚刚好超过容量限制。
其他的包都只有几 K 到几十 K。

想同时加上 ZeroTier 和 VMess 支持，如果不做其他修改的话，是不可能的。

要么去掉 ZeroTier，要么去掉一大堆其他包，而后者明显有悖于 Project Railgun 宗旨，「在不同的硬件上尽可能提供相同体验」。

另外提醒一下，WireGuard 组件加一起也占不了几十 K，并且也能用作内网穿透。

建议：
- 自行编译：本地编译真的不难，网上教程太多了。
- 更换硬件：K2P 确实太老了，纯 AP 是 K2P 的最终归宿，或者你也可以换 Padavan 试试。
- 换用 WireGuard 进行内网穿透。

**Comment by xmyaaa** [comment]
谢谢大佬回复，我己买了一个RAX3000M，正在学习编译，如有不懂，还会来请教大佬。

**Comment by xmyaaa** [comment]
> ![图像](https://private-user-images.githubusercontent.com/17025286/305597439-a8bd5202-71fd-4e2c-97a7-0753a4c079f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjU1MjMsIm5iZiI6MTcxMDE2NTIyMywicGF0aCI6Ii8xNzAyNTI4Ni8zMDU1OTc0MzktYThiZDUyMDItNzFmZC00ZTJjLTk3YTctMDc1M2E0YzA3OWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEzNTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZmFhZDIyNTk3ZjZkOThjY2VkMTMyZWExNmM3MTA2MjIzN2E5M2MzNTNlOWFmMzE0ZmU3NTYzNGNhOTBjYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W9iw5JYmC0Wc7N2H0YY0HDXoFQqryM1FeeKzCGYwuQA) ZeroTier一个包刚刚好超过容量限制。 其他的包都只有几K到几十K。
> 
> 想同时加上 ZeroTier 和 VMess 的支持，如果不做其他修改的话，是不可能的。
> 
> 或者删除 ZeroTier，或者删除一大堆其他包，而突然明显有悖于 Project Railgun 真理，「在不同的硬件上获取相同的体验」。
> 
> 或者更极端点，修改源码把早已被移除掉的 upx 加回来。但这件事我不太可能也没有动力去做的。
> 
> 另外提醒一下，WireGuard组件加在一起也占不了几十K，而且也能内置内网一下。
> 
> 建议：
> 
> * 自行编译：本地编译真的不难，网上教程太多了。
> * 更换硬件：K2P确实太老了，纯AP是K2P的最终归宿，或者你也可以换Padavan试试。
> * 换用WireGuard进行内网检查。

谢谢大佬回复，我已经买了一个RAX3000M，正在学习编译，如有不懂，还会来请教大佬。
